n = input('Digite algo:')
print('O tipo primitivo desse valor é', type(n))
print ('Só tem espaços?', n.isspace())
print ('é um número?', n.isnumeric())
print (' é alfabetico?', n.isalpha())
print ('é alfanumerico?', n.isalnum())
print ('esta em maiusculas?', n.isupper())
print ('esta em minisculas?', n.islower())
print ('esta capitalizada?', n.istitle())