nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando o seu nome:')
print('O nome em letras maiusculas é: ',nome.upper())
print ('O nome em letras minisculas é: ',nome.lower())
print ('O nome completo possui {} letras'.format(len(nome)-nome.count(' ')))
#print ('Seu primeiro nome tem {} letras' .format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))